export const mockJeans = [
  {
    article: 'Jeans',
    uid: '011100', // first 2 digits: identity, 3rd digit: 1 for jeans, 456th digits: price
    price: 100,
    color: 'Blue',
    size: 32,
    numberOfPockets: 4,
  },
  {
    article: 'Jeans',
    uid: '021100',
    price: 100,
    color: 'Blue',
    size: 32,
    numberOfPockets: 4,
  },
  {
    article: 'Jeans',
    uid: '031150',
    price: 150,
    color: 'Black',
    size: 34,
    numberOfPockets: 3,
  },
  {
    article: 'Jeans',
    uid: '041150',
    price: 150,
    color: 'White',
    size: 34,
    numberOfPockets: 3,
  },
  {
    article: 'Jeans',
    uid: '051200',
    price: 200,
    color: 'Blue',
    size: 36,
    numberOfPockets: 4,
  },
  {
    article: 'Jeans',
    uid: '061200',
    price: 200,
    color: 'Black',
    size: 36,
    numberOfPockets: 3,
  },
  {
    article: 'Jeans',
    uid: '071250',
    price: 250,
    color: 'Blue',
    size: 32,
    numberOfPockets: 4,
  },
  {
    article: 'Jeans',
    uid: '081250',
    price: 250,
    color: 'Yellow',
    size: 32,
    numberOfPockets: 3,
  },
  {
    article: 'Jeans',
    uid: '091300',
    price: 300,
    color: 'Blue',
    size: 34,
    numberOfPockets: 4,
  },
  {
    article: 'Jeans',
    uid: '101300',
    price: 300,
    color: 'Red',
    size: 30,
    numberOfPockets: 2,
  },
];

export const mockTShirts = [
  {
    article: 'T-Shirt',
    uid: '012100',
    price: 100,
    color: 'White',
    size: 'S',
    material: 'cotton',
  },
  {
    article: 'T-Shirt',
    uid: '022100',
    price: 100,
    color: 'Black',
    size: 'S',
    material: 'cotton',
  },
  {
    article: 'T-Shirt',
    uid: '032100',
    price: 100,
    color: 'Grey',
    size: 'M',
    material: 'cotton',
  },
  {
    article: 'T-Shirt',
    uid: '042100',
    price: 100,
    color: 'White',
    size: 'L',
    material: 'cotton',
  },
  {
    article: 'T-Shirt',
    uid: '052100',
    price: 100,
    color: 'White',
    size: 'XL',
    material: 'cotton',
  },
  {
    article: 'T-Shirt',
    uid: '062200',
    price: 200,
    color: 'White',
    size: 'S',
    material: 'Cotton and linen',
  },
  {
    article: 'T-Shirt',
    uid: '072200',
    price: 200,
    color: 'Red',
    size: 'M',
    material: 'Cotton and linen',
  },
  {
    article: 'T-Shirt',
    uid: '082200',
    price: 200,
    color: 'Grey',
    size: 'L',
    material: 'Cotton and linen',
  },
  {
    article: 'T-Shirt',
    uid: '092200',
    price: 200,
    color: 'White',
    size: 'XL',
    material: 'Cotton and linen',
  },
  {
    article: 'T-Shirt',
    uid: '102200',
    price: 200,
    color: 'Green',
    size: 'S',
    material: 'Cotton and linen',
  },
];

export const mockDresses = [
  {
    article: 'Dress',
    uid: '013100',
    price: 100,
    color: 'Red',
    size: 'XS',
    length: 'Above the knee',
  },
  {
    article: 'Dress',
    uid: '023100',
    price: 100,
    color: 'Blue',
    size: 'XS',
    length: 'Above the knee',
  },
  {
    article: 'Dress',
    uid: '033100',
    price: 100,
    color: 'Red',
    size: 'S',
    length: 'Above the knee',
  },
  {
    article: 'Dress',
    uid: '043100',
    price: 100,
    color: 'Red',
    size: 'M',
    length: 'Above the knee',
  },
  {
    article: 'Dress',
    uid: '053100',
    price: 100,
    color: 'Blue',
    size: 'L',
    length: 'Above the knee',
  },
  {
    article: 'Dress',
    uid: '063200',
    price: 200,
    color: 'Red',
    size: 'XS',
    length: 'Bellow the knee',
  },
  {
    article: 'Dress',
    uid: '073200',
    price: 200,
    color: 'Blue',
    size: 'S',
    length: 'Bellow the knee',
  },
  {
    article: 'Dress',
    uid: '083200',
    price: 200,
    color: 'Red',
    size: 'S',
    length: 'Bellow the knee',
  },
  {
    article: 'Dress',
    uid: '093200',
    price: 200,
    color: 'Red',
    size: 'M',
    length: 'Bellow the knee',
  },
  {
    article: 'Dress',
    uid: '103200',
    price: 200,
    color: 'Blue',
    size: 'L',
    length: 'Bellow the knee',
  },
];
